sudo: required
dist: trusty
services:
  - docker
language: generic
compiler:
  - gcc
notifications:
  email:
    recipients:
      - stephenbrawner@picknik.ai
env:
  matrix:
    - ROS_DISTRO=crystal  ROS_REPO=ros-shadow-fixed UPSTREAM_WORKSPACE=./example_python.repos
script:
  - source .travis/travis.sh
addons:
  # https://docs.travis-ci.com/user/ssh-known-hosts/
  ssh_known_hosts:
    - bitbucket.org
