image: ros:crystal-ros-core-bionic

variables:
  GIT_SUBMODULE_STRATEGY: recursive

colcon:
  stage: build_test
  script:
     - source ros2_gitlab_ci/gitlab_ros2.bash >/dev/null
     - colcon build --event-handlers console_direct+
     - colcon test --event-handlers console_direct+
