image: ros:crystal-ros-core-bionic

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
 - echo "Current working directory $(pwd)"
 - ls
 - ls ..
 - source ros2_gitlab_ci/gitlab_ros2.bash >/dev/null

colcon build:
  stage: build
  script:
    - colcon build

colcon test:
  stage: test
  script:
    - colcon test
