image: ros:crystal-ros-core-bionic

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
 - source ros2_gitlab_ci/gitlab_ros2.bash >/dev/null

colcon build:
  stage: build
  script:
    - colcon build --event-handlers console_direct+

colcon test:
  stage: test
  script:
    - colcon test --event-handlers console_direct+
